name: Push to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker buildx create --use
          docker buildx inspect default --bootstrap
          docker buildx build --platform linux/amd64,linux/arm64 -t $DOCKERHUB_USERNAME/reza1996:${{ github.sha }} . --push
